In [1]:
import numpy as np

#### 1.创建ndarray对象

In [4]:
n1 = np.array([1.0, 2.0, 3.0], dtype=np.float32)
n2 = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
n3 = np.array(['a', 'b', 'c'], dtype='|S1')

print("\nn1: \n", n1)
print("\nn2: \n", n2)
print("\nn3: \n", n3)


n1: 
 [ 1.  2.  3.]

n2: 
 [[1 2 3]
 [4 5 6]]

n3: 
 [b'a' b'b' b'c']


#### 2.访问ndarray对象的type、shape、ndim、size、dtype、itemsize和data属性

In [9]:
print("type: ", type(n1))
print("shape: ", n1.shape)
print("ndim: ", n1.ndim)
print("size: ", n1.size)
print("dtype: ", n3.dtype)
print("itemsize: ", n1.itemsize)
print("data: ", n1.data)

type:  <class 'numpy.ndarray'>
shape:  (3,)
ndim:  1
size:  3
dtype:  |S1
itemsize:  4
data:  <memory at 0x000001EF7E898708>


#### 3.创建数组:列表/元组/列表-元组混合方式

In [13]:
# 以列表的形式创建ndarray对象
v1 = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
print("\nv1: \n", v1)

# 以元组的形式创建ndarray对象
v2 = np.array(((1.0, 2.0, 3.0), (4.0, 5.0, 6.0)))
print("\nv2: \n", v2)

# 以列表和元组混合形式创建ndarray对象
v3 = np.array([(1.0, 2.0, 3.0), [4.0, 5.0, 6.0]])
print("\nv3: \n", v3)


v1: 
 [[ 1.  2.  3.]
 [ 4.  5.  6.]]

v2: 
 [[ 1.  2.  3.]
 [ 4.  5.  6.]]

v3: 
 [[ 1.  2.  3.]
 [ 4.  5.  6.]]


#### 4.自带的数组创建方法

- np.zeros()
- np.ones()
- np.arange()
- np.arange().reshape()
- np.linspace()
- np.random.random()
- np.random.randint()


In [15]:
v1 = np.zeros((2, 3))
print("v1: \n", v1)

v2 = np.ones((2, 3))
print("\nv2: \n", v2)

v3 = np.arange(0, 10, 2)
v4 = np.arange(0, 10, 2.5)
v5 = np.arange(0, 10, 2.5).reshape(2, 2)
print("\nv3: \n", v3)
print("v4: \n", v4)
print("v5: \n", v5)

v6 = np.linspace(0, 1.5, 5)
print("v6: \n", v6)

v7 = np.random.random((2, 3))
print("\nv7: \n", v7)

v8 = np.random.randint(1, 5, size=(3, 4))
print("\nv8: \n", v8)

v1: 
 [[ 0.  0.  0.]
 [ 0.  0.  0.]]

v2: 
 [[ 1.  1.  1.]
 [ 1.  1.  1.]]

v3: 
 [0 2 4 6 8]
v4: 
 [ 0.   2.5  5.   7.5]
v5: 
 [[ 0.   2.5]
 [ 5.   7.5]]
v6: 
 [ 0.     0.375  0.75   1.125  1.5  ]

v7: 
 [[ 0.69157966  0.63216217  0.24791072]
 [ 0.80385918  0.72684532  0.3107819 ]]

v8: 
 [[1 3 4 3]
 [1 1 2 3]
 [1 2 3 3]]
