In [5]:
import numpy as np

#### 1.算术运算

In [6]:
a = np.array([[1.0, 2.0, 3.0],[4.0, 5.0, 6.0]])
b = np.array([[2.0, 3.0, 4.0], [5.0, 6.0, 7.0]])

# 计算加法
print("a+b: \n", a+b)
print("a+1: \n", a+1)

# 计算减法
print("\na-b: \n", a-b)
print("\na-1: \n", a-1)

# 乘法
print("\na*b: \n", a*b)
print("\na*4: \n", a*4)

# 除法
print("\na/b: \n", a/b)
print("\na/2: \n", a/2)

a+b: 
 [[  3.   5.   7.]
 [  9.  11.  13.]]
a+1: 
 [[ 2.  3.  4.]
 [ 5.  6.  7.]]

a-b: 
 [[-1. -1. -1.]
 [-1. -1. -1.]]

a-1: 
 [[ 0.  1.  2.]
 [ 3.  4.  5.]]

a*b: 
 [[  2.   6.  12.]
 [ 20.  30.  42.]]

a*4: 
 [[  4.   8.  12.]
 [ 16.  20.  24.]]

a/b: 
 [[ 0.5         0.66666667  0.75      ]
 [ 0.8         0.83333333  0.85714286]]

a/2: 
 [[ 0.5  1.   1.5]
 [ 2.   2.5  3. ]]


#### 2.矩阵运算

In [9]:
a = np.arange(0, 6).reshape(2, 3)
b = np.ones((3, 2))

print("a x b: \n", np.dot(a, b))
print("\na x b: \n", a.dot(b))

a x b: 
 [[  3.   3.]
 [ 12.  12.]]

a x b: 
 [[  3.   3.]
 [ 12.  12.]]


#### 3.自增和自减运算

In [14]:
a = np.arange(0, 4, dtype=np.float32)

a += 1.0
print("a += 1: \n", a)

a *= 2.0
print("\na *= 2: \n", a)

a -= 1.0
print("\na -= 1: \n", a)

a /= 2.0
print("\na /= 2: \n", a)

a += 1: 
 [ 1.  2.  3.  4.]

a *= 2: 
 [ 2.  4.  6.  8.]

a -= 1: 
 [ 1.  3.  5.  7.]

a /= 2: 
 [ 0.5  1.5  2.5  3.5]


#### 4.库函数

- np.sqrt()
- np.sin()
- np.log()
- np.sum()
- np.min()
- np.max()

In [18]:
a = np.arange(1, 5, dtype=np.float32).reshape(2, 2)

print("sqrt: ", np.sqrt(a))
print("sin: ", np.sin(a))
print("log: ", np.log(a))
print("sum: ", np.sum(a))
print("min: ", np.min(a))
print("max: ", np.max(a))

sqrt:  [[ 1.          1.41421354]
 [ 1.73205078  2.        ]]
sin:  [[ 0.84147096  0.90929741]
 [ 0.14112    -0.7568025 ]]
log:  [[ 0.          0.69314718]
 [ 1.09861231  1.38629436]]
sum:  10.0
min:  1.0
max:  4.0
