In [1]:
import numpy as np

#### 1.bool矩阵

In [4]:
a = np.random.randint(1, 10, size=(5, 5))
print("a: \n", a)

print("a < 5: \n", a < 5)

a: 
 [[2 8 6 6 5]
 [3 8 8 3 9]
 [6 6 7 2 2]
 [3 3 8 6 8]
 [6 1 7 6 8]]
a < 5: 
 [[ True False False False False]
 [ True False False  True False]
 [False False False  True  True]
 [ True  True False False False]
 [False  True False False False]]


#### 2.条件矩阵

In [5]:
a = np.random.randint(1, 10, size=(5, 5))

print("a: \n", a)
print("\n bool a < 5: \n", a < 5)
print("\n 条件矩阵:打印小于5的矩阵元素: \n", a[a<5])

a: 
 [[2 9 1 6 6]
 [3 6 6 1 8]
 [7 7 6 1 4]
 [4 5 2 5 3]
 [7 1 2 8 2]]

 bool a < 5: 
 [[ True False  True False False]
 [ True False False  True False]
 [False False False  True  True]
 [ True False  True False  True]
 [False  True  True False  True]]

 条件矩阵:打印小于5的矩阵元素: 
 [2 1 3 1 1 4 4 2 3 1 2 2]
