In [1]:
import numpy as np

#### 1.形状变换

- ndarray.reshape()：改变形状，返回新的矩阵
- ndarray.shape=():修改本地矩阵的形状
- ndarray.rave() ：把二维矩阵变成一维矩阵
- ndarray.transpose():矩阵转置

In [5]:
a = np.arange(0, 15)
print("a: \n", a)

b = a.reshape(3, 5)
a.shape = (3, 5)
print("b: \n", b)
print("a: \n", a)

print("a.ravel(): \n", a.ravel())
print("a.transpose(): \n", a.transpose())

a: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
b: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
a: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
a.ravel(): 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
a.transpose(): 
 [[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
