In [1]:
import numpy as np

#### 1.对象副本与视图

- 对象的副本:与对象指向的内存不同；例子:ndarray.copy()操作
- 对象的视图:与对象指向同一个内存；例如赋值操作、切片操作

In [15]:
a = np.arange(10)

# 副本
b = a.copy()
b[0] = 1
print("a: ", a)
print("b: ", b)
print("id(a) ", id(a)) # 可以看到两者的地址是不一样的
print("id(b) ", id(b))

# 视图操作
c = a
d = a[1:10:2]
print("\nid(a): ", id(a)) # 可以看到三者的地址是一样的
print("id(c): ", id(c))
print("id(d): ", id(d))

a:  [0 1 2 3 4 5 6 7 8 9]
b:  [1 1 2 3 4 5 6 7 8 9]
id(a)  2919296381616
id(b)  2919296381056

id(a):  2919296381616
id(c):  2919296381616
id(d):  2919296381376


#### 2.向量化

矩阵之间的运算可以通过类似数学运算的形式进行，例如:矩阵之间的元素级运算 $A*B$,$A+B$

#### 3.广播机制

广播机制：实现不同shape矩阵之间的运算或者函数处理。

广播机制的兼容性条件有以下几条(满足其中之一即可使用广播机制)
1. 两个矩阵之间的各个维度等长
2. 其中一个矩阵的维度为1(缺失的数据使用维度1中的数据填充)

In [18]:
a = np.arange(16).reshape(4, 4)
b = np.ones((4))
print("a: \n", a)
print("b: \n", b)

# b会使用广播机制扩充到[4,4]
c = a + b
print("c: \n", c)

%timeit d = np.arange(6).reshape(2, 1, 3)
e = np.arange(6).reshape(2, 3, 1)
f = d + e # 存在维度1，d\e都会进行扩维
print("\nf.shape: ", f.shape)
print("d: \n", d)
print("e: \n", e)
print("f: \n", f)
%time

a: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
b: 
 [ 1.  1.  1.  1.]
c: 
 [[  1.   2.   3.   4.]
 [  5.   6.   7.   8.]
 [  9.  10.  11.  12.]
 [ 13.  14.  15.  16.]]
1.02 µs ± 8.64 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

f.shape:  (2, 3, 5)
d: 
 [1 3 5 7 9]
e: 
 [[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]]
f: 
 [[[ 1  3  5  7  9]
  [ 2  4  6  8 10]
  [ 3  5  7  9 11]]

 [[ 4  6  8 10 12]
  [ 5  7  9 11 13]
  [ 6  8 10 12 14]]]
Wall time: 0 ns
