In [2]:
import numpy as np

#### 1. 二进制文件读写

- np.save():以二进制的方式保存文件到数据中
- np.load():加载二进制文件

In [6]:
data = np.random.rand(5, 5)
print("data: \n", data)

# 以二进制保存数据
np.save("data.b", data)
# 以文本形式保存数据
np.savetxt("data.txt", data)

# 读取二进制文本
load_data_b = np.load("data.b.npy")
print("\n load_data_b: \n", load_data_b)
# 读取文本形式的文本
load_data_txt = np.loadtxt("data.txt")
print("\n load_data_txt: \n", load_data_txt)

data: 
 [[ 0.2618988   0.30479602  0.7307923   0.49616699  0.47594052]
 [ 0.02397009  0.33996271  0.62041845  0.89919974  0.08377456]
 [ 0.83987029  0.66270435  0.57482151  0.39971126  0.20423299]
 [ 0.23764856  0.13435936  0.79198312  0.04730726  0.25825767]
 [ 0.09417188  0.85382959  0.5154922   0.62929393  0.99647136]]

 load_data_b: 
 [[ 0.2618988   0.30479602  0.7307923   0.49616699  0.47594052]
 [ 0.02397009  0.33996271  0.62041845  0.89919974  0.08377456]
 [ 0.83987029  0.66270435  0.57482151  0.39971126  0.20423299]
 [ 0.23764856  0.13435936  0.79198312  0.04730726  0.25825767]
 [ 0.09417188  0.85382959  0.5154922   0.62929393  0.99647136]]

 load_data_txt: 
 [[ 0.2618988   0.30479602  0.7307923   0.49616699  0.47594052]
 [ 0.02397009  0.33996271  0.62041845  0.89919974  0.08377456]
 [ 0.83987029  0.66270435  0.57482151  0.39971126  0.20423299]
 [ 0.23764856  0.13435936  0.79198312  0.04730726  0.25825767]
 [ 0.09417188  0.85382959  0.5154922   0.62929393  0.99647136]]


#### 2.读取文件中列表形式的数据

- 读取csv格式的数据
- np.genfromtxt("文件名", delimite="分隔符", names=是否有标题)
- np.genfromtxt的优点：能处理文件中丢失的数据,把空值自动填充为nan

In [14]:
%%writefile data.csv
id,value1,value2,value3
1,123,1.4,23
2,110,0.5,18
3,164,2.1,19
4,,0.39,20

Overwriting data.csv


In [16]:
# 读取csv文件
data = np.genfromtxt("data.csv", delimiter=',', names=True)
print("data: \n", data)

# 访问数据
print("data: ", data["id"])
print("data: ", data[2])
print("data: ", data["id"][2])
print("data: ", data[2]["id"])

data: 
 [( 1.,  123.,  1.4 ,  23.) ( 2.,  110.,  0.5 ,  18.)
 ( 3.,  164.,  2.1 ,  19.) ( 4.,   nan,  0.39,  20.)]
data:  [ 1.  2.  3.  4.]
data:  ( 3.,  164.,  2.1,  19.)
data:  3.0
data:  3.0
